# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe69e528baecc4d087c2511ffb374c34277206177e25564acf61993942dd55ba7607f8ab5d96301b8c4bf0ff60b97e51fa6cd2dc32453f39aeaca3bf125904fa

test:
  secret_key_base: f727821640f7b92840875210784dae4d62ca3013d218e5f9caec640be1a525c4edf47f9db5c7cb04b2e4774a228b22491c58549d4186a8a0a4298808a8ab1c22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
